version: '2'
services:
  web:
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5433/webservice
      SPRING_DATASOURCE_USERNAME: demo
      SPRING_DATASOURCE_PASSWORD: demo
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - 8080:8080
    depends_on:
      - db
  db:
    image: 'postgres:13.6'
    expose:
      - 5433
    ports:
      - 5433:5433
    environment:
      POSTGRES_USER: demo
      POSTGRES_PASSWORD: demo
      POSTGRES_DB: webservice
    command:
      -p 5433